### ISSUE TITLE
Red error bar.

### ISSUE THREAD

**Issue by redstreet** [seltzered/fava-classy-portfolio#3]
When I try this out, I simply get this in a red bar in fava:

```
Loading http://localhost:8081/main-accounts/extension/FavaClassyPortfolio/ failed.
```

There is no error output on the console where I started fava. How do I debug this? Thanks!

_Originally posted by @redstreet in https://github.com/seltzered/fava-classy-portfolio/issues/1#issuecomment-562992486_

**Comment by seltzered** [comment]
Haven't forgotten about this, just haven't had time. Will try to take a look tomorrow. The last todo note I had when trying to look at this was finding some way to add traceback printing. 

If you have an example file of where things are failing that's a bit closer to your use that'll help. Think one example i had was mispelling things in the options list (e.g. 'account_open_mettttttdata_pattern' )

**Comment by redstreet** [comment]
Thanks a bunch! Unfortunately, it doesn't fail on any of my simpler examples, but only on my actual source. So I've not easily been able to narrow down the problem. Which is why I was trying to figure out how to obtain a traceback :).

**Comment by seltzered** [comment]
I should refactor this, but just to hastily try something try the latest commit: https://github.com/seltzered/fava-classy-portfolio/commit/5732cac58413bed0d1845052fbac83c55df0f405

**Comment by redstreet** [comment]
Thanks! I can see the trace now and added prints, but need help interpreting what's occurring:

```
Traceback (most recent call last):
  File "__init__.py", line 82, in portfolio_accounts
    True),
  File "__init__.py", line 403, in insert_rowspans
    False)
  File "__init__.py", line 438, in insert_rowspans
    False)
  File "__init__.py", line 460, in insert_rowspans
    data[key][coltype[0]], {"rowspan": 1})
KeyError: 'asset_subclass_allocation'
```

```
key = nosubclass
coltype == ('asset_subclass_allocation', "<class 'plugins.fava-classy-portfolio.DecimalPercent'>") 
```

data[nosubclass] exists but that dictionary, of course, doesn't contain 'asset_subclass_allocation'

Any leads appreciated, thanks.

**Comment by seltzered** [comment]
Huh, similar issue to what @grostim was having in #4 , have you looked at my [example project](https://github.com/seltzered/fava-classy-portfolio-demo) to get an idea of what could be different?  Are your accounts using a non-english language?

(My mind hasn't been in this space in a while so may have another reply later.)

**Comment by redstreet** [comment]
The example works fine. I can't tell how my sources could be different. No other character set.

Sure, sounds good. Regardless of this issue, your plugin is a helpful example for other plugins I want to write, so thanks for that!
